
variable "prefix" {
  type    = string
  default = "sample_fastapi_2"
}

variable "function_name" {
  type    = string
  default = "app"
}

# name of zip file to deploy, generated by createZip.py
variable "zip_file_name" {
  type    = string
  default = "codeTF.zip"
}